-- ==============================================================================
-- SEED DATA generated from the app's local Pan-India dataset (src/data/*.ts)
-- Safe to re-run: every insert uses ON CONFLICT (id) DO NOTHING.
-- Run this in the Supabase SQL Editor AFTER running schema.sql.
-- ==============================================================================

-- 1. Cities
insert into cities (id, name, state, center_lat, center_lng) values ('delhi', 'Delhi NCR', 'Delhi', 28.6506, 77.2303) on conflict (id) do nothing;
insert into cities (id, name, state, center_lat, center_lng) values ('mumbai', 'Mumbai', 'Maharashtra', 18.9322, 72.8335) on conflict (id) do nothing;
insert into cities (id, name, state, center_lat, center_lng) values ('jaipur', 'Jaipur', 'Rajasthan', 26.9239, 75.8267) on conflict (id) do nothing;
insert into cities (id, name, state, center_lat, center_lng) values ('kochi', 'Kochi (Cochin)', 'Kerala', 9.9658, 76.2421) on conflict (id) do nothing;
insert into cities (id, name, state, center_lat, center_lng) values ('kolkata', 'Kolkata', 'West Bengal', 22.5726, 88.3639) on conflict (id) do nothing;
insert into cities (id, name, state, center_lat, center_lng) values ('varanasi', 'Varanasi (Benares)', 'Uttar Pradesh', 25.3076, 83.0107) on conflict (id) do nothing;
insert into cities (id, name, state, center_lat, center_lng) values ('bengaluru', 'Bengaluru', 'Karnataka', 12.9716, 77.5946) on conflict (id) do nothing;
insert into cities (id, name, state, center_lat, center_lng) values ('chennai', 'Chennai', 'Tamil Nadu', 13.0336, 80.2699) on conflict (id) do nothing;
insert into cities (id, name, state, center_lat, center_lng) values ('hyderabad', 'Hyderabad', 'Telangana', 17.3616, 78.4747) on conflict (id) do nothing;
insert into cities (id, name, state, center_lat, center_lng) values ('goa', 'Goa', 'Goa', 15.4989, 73.8278) on conflict (id) do nothing;

-- 2. Vendors (one per vendor referenced in the experiences below)
-- auth_user_id is left NULL: the app does not yet authenticate vendors via
-- Supabase Auth, so these are seeded as unclaimed/verified demo vendors.
insert into vendors (id, business_name, city_id, established_year, verified) values ('dec4c976-2fb4-4af5-806e-a2ef972eb05e', 'Pandit Gaya Prasad Parantha Guild', 'delhi', 1872, true) on conflict (id) do nothing; -- was local id: v-delhi-01
insert into vendors (id, business_name, city_id, established_year, verified) values ('9fdc2664-eff6-430e-abfa-86b9fc9333ac', 'Nizamuddin Heritage Preservation Trust', 'delhi', 1325, true) on conflict (id) do nothing; -- was local id: v-delhi-02
insert into vendors (id, business_name, city_id, established_year, verified) values ('0bb70b1d-f1e4-45f8-a99a-c96c5df728ef', 'Mitti Studio Collective', 'delhi', 2011, true) on conflict (id) do nothing; -- was local id: v-delhi-03
insert into vendors (id, business_name, city_id, established_year, verified) values ('f46e1f65-5453-4d61-8678-3256c5af6a7e', 'Bastian & Yazdani Heritage Walkers', 'mumbai', 1953, true) on conflict (id) do nothing; -- was local id: v-mum-01
insert into vendors (id, business_name, city_id, established_year, verified) values ('4777e603-b82e-41a0-bb01-168720b7dad2', 'Dadar Phool Galli Traders', 'mumbai', 1938, true) on conflict (id) do nothing; -- was local id: v-mum-02
insert into vendors (id, business_name, city_id, established_year, verified) values ('7591c564-63ea-4a15-9a13-94c68f622dc9', 'Chhipa Mohalla Artisan Cooperative', 'jaipur', 1888, true) on conflict (id) do nothing; -- was local id: v-jai-01
insert into vendors (id, business_name, city_id, established_year, verified) values ('a91eccd8-05c8-4a9d-af3b-b233341f40a0', 'Surana Heritage Gem Guild', 'jaipur', 1735, true) on conflict (id) do nothing; -- was local id: v-jai-02
insert into vendors (id, business_name, city_id, established_year, verified) values ('b7703866-2422-4de1-8190-e10511827327', 'Malabar Heritage Spice Guild', 'kochi', 1924, true) on conflict (id) do nothing; -- was local id: v-koc-01
insert into vendors (id, business_name, city_id, established_year, verified) values ('979b01c8-3d2d-4d2e-8d5d-9ee1318eefa1', 'Kerala Kathakali Centre Trust', 'kochi', 1982, true) on conflict (id) do nothing; -- was local id: v-koc-02
insert into vendors (id, business_name, city_id, established_year, verified) values ('6d612990-8ee6-449b-8863-2ccc74c64fe5', 'Subah-e-Banaras Boat Guild', 'varanasi', 1970, true) on conflict (id) do nothing; -- was local id: v-var-01
insert into vendors (id, business_name, city_id, established_year, verified) values ('092ca264-504b-48b9-91fd-fb8bbf5bb177', 'Ansari Silk Weaving Lineage', 'varanasi', 1845, true) on conflict (id) do nothing; -- was local id: v-var-02
insert into vendors (id, business_name, city_id, established_year, verified) values ('2f6d1e51-f890-4b4f-ae31-4fe16f130ad8', 'Kumartuli Paul Sculptors Guild', 'kolkata', 1757, true) on conflict (id) do nothing; -- was local id: v-kol-01
insert into vendors (id, business_name, city_id, established_year, verified) values ('d09850d8-dc33-4ff4-a214-19e989ae0fed', 'CTR & Veena Tiffin Society', 'bengaluru', 1968, true) on conflict (id) do nothing; -- was local id: v-blr-01
insert into vendors (id, business_name, city_id, established_year, verified) values ('864d84ec-3cdd-4d46-aed3-57f7442976b9', 'Kapaleeshwarar Heritage Kitchen Collective', 'chennai', 1962, true) on conflict (id) do nothing; -- was local id: v-che-01
insert into vendors (id, business_name, city_id, established_year, verified) values ('0b388a00-f947-49ab-a918-ea77e3e8e549', 'Thanjavur Bronze & Wind Instrument Guild', 'chennai', 1901, true) on conflict (id) do nothing; -- was local id: v-che-02
insert into vendors (id, business_name, city_id, established_year, verified) values ('7722c2f0-46c7-4358-92ea-659f61754c60', 'Asghar Ali Nizami Perfumers', 'hyderabad', 1894, true) on conflict (id) do nothing; -- was local id: v-hyd-01
insert into vendors (id, business_name, city_id, established_year, verified) values ('b6595d5a-7d03-4657-8f84-b744f26b591e', 'Velha Goa Ceramic Studios', 'goa', 1992, true) on conflict (id) do nothing; -- was local id: v-goa-01

-- 3. Experiences
insert into experiences (id, experience_title, category, duration_minutes, price_per_head, maximum_capacity, lat, lng, city_id, neighborhood, tags, specialty_tier, vendor_id, one_line_teaser, full_description, indoor, wheelchair, step_free, senior_paced, low_sensory, hours, open_now, images, rating_score, rating_review_count, editorial_note, data_source, attribution, eligible_for_nearby_promotions) values ('exp-delhi-01', 'Chandni Chowk 150-Year Paranthe & Spice Alleys Heritage Walk', 'food', 90, 350, 10, 28.6562, 77.2309, 'delhi', 'Old Delhi / Gali Paranthe Wali', ARRAY['street food', 'heritage', 'paranthe', 'khari baoli spices', 'independent'], 'hidden-gem', 'dec4c976-2fb4-4af5-806e-a2ef972eb05e', 'Taste wood-fired stuffed paranthas and explore centuries-old spice cellars in Shahjahanabad with a neighborhood food historian.', 'Stepping into the narrow stone bylanes behind the historic Gurudwara Sis Ganj, this morning walk leads travelers through fourth-generation culinary institutions. Guests taste stuffed rabri, mooli, and bitter gourd paranthas fried in iron karahis, followed by freshly ground heirloom garam masalas inside the wholesale courtyards of Khari Baoli.', false, false, false, true, false, '08:30 - 15:30 (Daily)', true, ARRAY['https://images.unsplash.com/photo-1589301760014-d929f3979dbc?auto=format&fit=crop&w=900&q=80', 'https://images.unsplash.com/photo-1601050690597-df0568f70950?auto=format&fit=crop&w=900&q=80'], 4.92, 148, 'Raw culinary authenticity with respectful passage through historic living neighborhoods.', 'curated_seed', 'Wikimedia Commons (CC BY-SA 4.0) / OpenStreetMap Contributors', true) on conflict (id) do nothing;
insert into experiences (id, experience_title, category, duration_minutes, price_per_head, maximum_capacity, lat, lng, city_id, neighborhood, tags, specialty_tier, vendor_id, one_line_teaser, full_description, indoor, wheelchair, step_free, senior_paced, low_sensory, hours, open_now, images, rating_score, rating_review_count, editorial_note, data_source, attribution, eligible_for_nearby_promotions) values ('exp-delhi-02', 'Nizamuddin Basti Sufi Qawwali & Stepwell Sanctuary', 'culture', 75, 0, 25, 28.5916, 77.2422, 'delhi', 'Hazrat Nizamuddin Aulia Precinct', ARRAY['sufi poetry', 'qawwali', 'stepwell baoli', 'spiritual', 'heritage'], 'signature', '9fdc2664-eff6-430e-abfa-86b9fc9333ac', 'Listen to devotional harmonium rhythms in the marble courtyard and explore the 700-year restored baoli.', 'An ancient residential enclave that has hosted musical devotion for seven centuries. Led by community heritage custodians, visitors sit quietly in the courtyard listening to descendants of Amir Khusro recite devotional verses, before walking down the step-free restoration ramps to view the freshwater stepwell.', true, true, true, true, false, '17:00 - 21:00 (Thu - Sun)', false, ARRAY['https://images.unsplash.com/photo-1548013146-72479768bada?auto=format&fit=crop&w=900&q=80', 'https://images.unsplash.com/photo-1599661046289-e31897846e41?auto=format&fit=crop&w=900&q=80'], 4.96, 310, 'Unmatched spiritual acoustics and tranquil architectural restoration.', 'curated_seed', 'Wikimedia Commons (CC BY-SA 4.0)', true) on conflict (id) do nothing;
insert into experiences (id, experience_title, category, duration_minutes, price_per_head, maximum_capacity, lat, lng, city_id, neighborhood, tags, specialty_tier, vendor_id, one_line_teaser, full_description, indoor, wheelchair, step_free, senior_paced, low_sensory, hours, open_now, images, rating_score, rating_review_count, editorial_note, data_source, attribution, eligible_for_nearby_promotions) values ('exp-delhi-03', 'Hauz Khas Terracotta & Studio Pottery Throwing', 'workshops', 90, 450, 6, 28.5494, 77.2001, 'delhi', 'Hauz Khas Village / Deer Park', ARRAY['clay pottery', 'terracotta', 'craftsman studio', 'hands-on'], 'hidden-gem', '0bb70b1d-f1e4-45f8-a99a-c96c5df728ef', 'Shape earthen chai kulhads and terracotta bowls on manual kick-wheels overlooking 14th-century madrasa ruins.', 'Founded by master ceramicists from Delhi Blue Pottery Trust, this quiet second-floor atelier teaches visitors traditional clay wedging, wheel throwing, and slip decoration. Guests pull two vessels using Yamuna silt clay formulations, which are kiln-fired and carefully packed.', true, false, false, true, true, '10:00 - 18:00 (Tue - Sun)', true, ARRAY['https://images.unsplash.com/photo-1565193566173-7a0ee3dbe261?auto=format&fit=crop&w=900&q=80', 'https://images.unsplash.com/photo-1578749556568-bc2c40e68b61?auto=format&fit=crop&w=900&q=80'], 4.88, 82, 'Patient instructors with tactile focus on local clay traditions.', 'curated_seed', 'OpenStreetMap Contributors', true) on conflict (id) do nothing;
insert into experiences (id, experience_title, category, duration_minutes, price_per_head, maximum_capacity, lat, lng, city_id, neighborhood, tags, specialty_tier, vendor_id, one_line_teaser, full_description, indoor, wheelchair, step_free, senior_paced, low_sensory, hours, open_now, images, rating_score, rating_review_count, editorial_note, data_source, attribution, eligible_for_nearby_promotions) values ('exp-mumbai-01', 'Kala Ghoda Art Deco & Historic Irani Chai Tasting', 'culture', 80, 280, 12, 18.9284, 72.8318, 'mumbai', 'Fort / Kala Ghoda', ARRAY['art deco', 'irani cafe', 'bun maska', 'heritage architecture', 'independent'], 'hidden-gem', 'f46e1f65-5453-4d61-8678-3256c5af6a7e', 'Walk through the second-largest Art Deco cluster in the world and sip cardamom chai with brun maska at an 80-year bakery.', 'Beginning outside the David Sassoon Library, this shaded walking route studies the distinctive ocean-liner balconies and relief sculptures of Oval Maidan. Concludes inside Yazdani Bakery, where the wood-fired ovens still bake crusty brun bread served with salted butter and sweet brewed Irani chai.', false, true, true, true, false, '08:00 - 18:00 (Mon - Sat)', true, ARRAY['https://images.unsplash.com/photo-1570168007204-dfb528c6958f?auto=format&fit=crop&w=900&q=80', 'https://images.unsplash.com/photo-1567157577867-05ccb1388e66?auto=format&fit=crop&w=900&q=80'], 4.93, 176, 'Exceptional blend of social history and authentic culinary memory.', 'curated_seed', 'Wikimedia Commons (CC BY-SA 4.0)', true) on conflict (id) do nothing;
insert into experiences (id, experience_title, category, duration_minutes, price_per_head, maximum_capacity, lat, lng, city_id, neighborhood, tags, specialty_tier, vendor_id, one_line_teaser, full_description, indoor, wheelchair, step_free, senior_paced, low_sensory, hours, open_now, images, rating_score, rating_review_count, editorial_note, data_source, attribution, eligible_for_nearby_promotions) values ('exp-mumbai-02', 'Dadar Morning Flower Market & Spiced Poha Breakfast', 'markets', 60, 150, 10, 19.0178, 72.8478, 'mumbai', 'Dadar West', ARRAY['flower market', 'marigold', 'street market', 'maharashtrian breakfast'], 'signature', '4777e603-b82e-41a0-bb01-168720b7dad2', 'Walk beneath suspended canopies of orange marigold garlands and taste warm kanda poha at an iconic corner stall.', 'Every morning at dawn, growers from Pune and Nashik unload towering baskets of jasmine, roses, and marigolds beneath the Dadar flyover. Visitors weave through wholesale bargaining stalls, watch rapid floral garland weaving, and conclude with authentic Maharashtrian breakfast.', false, true, true, true, false, '06:00 - 12:00 (Daily)', true, ARRAY['https://images.unsplash.com/photo-1596178065887-1198b6148b2b?auto=format&fit=crop&w=900&q=80', 'https://images.unsplash.com/photo-1513519245088-0e12902e5a38?auto=format&fit=crop&w=900&q=80'], 4.87, 94, 'Sensory vibrancy and genuine local wholesale trade.', 'curated_seed', 'OpenStreetMap Contributors', true) on conflict (id) do nothing;
insert into experiences (id, experience_title, category, duration_minutes, price_per_head, maximum_capacity, lat, lng, city_id, neighborhood, tags, specialty_tier, vendor_id, one_line_teaser, full_description, indoor, wheelchair, step_free, senior_paced, low_sensory, hours, open_now, images, rating_score, rating_review_count, editorial_note, data_source, attribution, eligible_for_nearby_promotions) values ('exp-jaipur-01', 'Bagru Mud-Resist Block Printing Workshop & Vegetable Dyes', 'workshops', 100, 500, 8, 26.8124, 75.5451, 'jaipur', 'Bagru Village Crafts Cluster', ARRAY['block printing', 'dabu mud resist', 'natural dyes', 'hands-on', 'independent'], 'hidden-gem', '7591c564-63ea-4a15-9a13-94c68f622dc9', 'Carve and hand-stamp cotton stoles using vintage teak woodblocks and fermented indigo vats.', 'Located in the historic Chhipa village, this family atelier preserves the centuries-old Dabu mud-resist printing technique. Guests learn to mix fuller earth and wheat chaff pastes, align intricate hand-carved woodblocks on stretched cotton fabric, and immerse their cloth into natural pomegranate and indigo dye pits.', true, true, true, true, true, '09:30 - 17:00 (Daily except Mon)', true, ARRAY['https://images.unsplash.com/photo-1542314831-068cd1dbfeeb?auto=format&fit=crop&w=900&q=80', 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=900&q=80'], 4.97, 220, 'Authentic artisan lineage with direct economic benefit to village printers.', 'curated_seed', 'Wikimedia Commons (CC BY-SA 4.0)', true) on conflict (id) do nothing;
insert into experiences (id, experience_title, category, duration_minutes, price_per_head, maximum_capacity, lat, lng, city_id, neighborhood, tags, specialty_tier, vendor_id, one_line_teaser, full_description, indoor, wheelchair, step_free, senior_paced, low_sensory, hours, open_now, images, rating_score, rating_review_count, editorial_note, data_source, attribution, eligible_for_nearby_promotions) values ('exp-jaipur-02', 'Johari Bazaar Kundan Gem Cutting & Sandalwood Tea', 'culture', 70, 320, 8, 26.9205, 75.8286, 'jaipur', 'Old Pink City / Johari Bazaar', ARRAY['gemstones', 'kundan jewelry', 'pink city', 'artisan craftsmanship'], 'signature', 'a91eccd8-05c8-4a9d-af3b-b233341f40a0', 'Observe stone cutters facet emeralds on wooden lapidary wheels and taste Sahu coal-roasted milk tea.', 'Commissioned when Maharaja Jai Singh II established Jaipur in 1727, Johari Bazaar remains India capital of precious stone cutting. In this private workshop visit, visitors observe lapidaries hand-cut and foil-set uncut polki diamonds into 24-karat gold lattices, followed by a tasting of slow-simmered cardamom tea.', true, true, true, true, true, '11:00 - 19:00 (Mon - Sat)', true, ARRAY['https://images.unsplash.com/photo-1599661046289-e31897846e41?auto=format&fit=crop&w=900&q=80', 'https://images.unsplash.com/photo-1548013146-72479768bada?auto=format&fit=crop&w=900&q=80'], 4.89, 110, 'Fascinating micro-precision craft preserved without commercial sales pressure.', 'curated_seed', 'OpenStreetMap Contributors', true) on conflict (id) do nothing;
insert into experiences (id, experience_title, category, duration_minutes, price_per_head, maximum_capacity, lat, lng, city_id, neighborhood, tags, specialty_tier, vendor_id, one_line_teaser, full_description, indoor, wheelchair, step_free, senior_paced, low_sensory, hours, open_now, images, rating_score, rating_review_count, editorial_note, data_source, attribution, eligible_for_nearby_promotions) values ('exp-kochi-01', 'Mattancherry Ancient Spice Warehouse Tasting & Pepper Grinding', 'food', 75, 250, 12, 9.9575, 76.2592, 'kochi', 'Mattancherry / Jew Town', ARRAY['tellicherry pepper', 'spice warehouse', 'cardamom auction', 'coastal heritage'], 'hidden-gem', 'b7703866-2422-4de1-8190-e10511827327', 'Sample sun-dried Tellicherry black peppercorns, green cardamom pods, and nutmeg inside a 100-year timber warehouse.', 'Bazaars in Mattancherry have exported Malabar spices across the Arabian Sea for millennia. At this heritage warehouse, guests smell fresh cloves, grade dried ginger roots, and taste cold-infused cardamom herbal drinks while observing traditional jute sack weighing scales.', true, true, true, true, true, '09:00 - 17:30 (Mon - Sat)', true, ARRAY['https://images.unsplash.com/photo-1596178065887-1198b6148b2b?auto=format&fit=crop&w=900&q=80', 'https://images.unsplash.com/photo-1547496502-affa22d38842?auto=format&fit=crop&w=900&q=80'], 4.91, 88, 'Aromatic depth and educational clarity away from tourist souvenir shops.', 'curated_seed', 'Wikimedia Commons (CC BY-SA 4.0)', true) on conflict (id) do nothing;
insert into experiences (id, experience_title, category, duration_minutes, price_per_head, maximum_capacity, lat, lng, city_id, neighborhood, tags, specialty_tier, vendor_id, one_line_teaser, full_description, indoor, wheelchair, step_free, senior_paced, low_sensory, hours, open_now, images, rating_score, rating_review_count, editorial_note, data_source, attribution, eligible_for_nearby_promotions) values ('exp-kochi-02', 'Fort Kochi Kathakali Mudra & Makeup Rehearsal Observation', 'culture', 90, 300, 16, 9.9671, 76.2445, 'kochi', 'Fort Kochi Heritage Zone', ARRAY['kathakali', 'traditional dance', 'facial makeup', 'classical arts'], 'signature', '979b01c8-3d2d-4d2e-8d5d-9ee1318eefa1', 'Observe classical dancers apply mineral face pigments and practice nuanced 24-mudra hand gestures.', 'In an intimate teak-wood amphitheater, visitors arrive early to watch performers spend two hours applying crushed stone pastes (chutti) to their faces. The master artist then breaks down the 9 rasas (emotional expressions) and rhythmic footwork of Kerala ancient dramatic tradition.', true, true, true, true, false, '17:00 - 20:30 (Daily)', false, ARRAY['https://images.unsplash.com/photo-1545569341-9eb8b30979d9?auto=format&fit=crop&w=900&q=80', 'https://images.unsplash.com/photo-1528164344705-475426879c0d?auto=format&fit=crop&w=900&q=80'], 4.95, 245, 'Rare patient demonstration honoring centuries of codified physical discipline.', 'curated_seed', 'Wikimedia Commons (CC BY-SA 4.0)', true) on conflict (id) do nothing;
insert into experiences (id, experience_title, category, duration_minutes, price_per_head, maximum_capacity, lat, lng, city_id, neighborhood, tags, specialty_tier, vendor_id, one_line_teaser, full_description, indoor, wheelchair, step_free, senior_paced, low_sensory, hours, open_now, images, rating_score, rating_review_count, editorial_note, data_source, attribution, eligible_for_nearby_promotions) values ('exp-varanasi-01', 'Kashi Dawn Rowing & Assi Ghat Classical Sitar Raga', 'nature', 80, 200, 10, 25.2925, 83.0069, 'varanasi', 'Assi Ghat & Tulsi Ghat', ARRAY['sunrise boat', 'ganga', 'classical sitar', 'morning raga', 'peaceful'], 'signature', '6d612990-8ee6-449b-8863-2ccc74c64fe5', 'Drift past ancient stone ghats at sunrise as morning ragas resonate from the riverbanks.', 'Beginning at 05:45 AM before city bustle awakes, an experienced local oarsman guides visitors in an acoustic wooden boat across the gentle morning waters of the Ganga. Listen to live sitar harmonies from Assi Ghat while watching dawn mist lift from 18th-century palatial facades.', false, false, false, true, true, '05:30 - 08:30 (Daily)', false, ARRAY['https://images.unsplash.com/photo-1561361513-2d000a50f0dc?auto=format&fit=crop&w=900&q=80', 'https://images.unsplash.com/photo-1548013146-72479768bada?auto=format&fit=crop&w=900&q=80'], 4.98, 360, 'Profound tranquility and respectful distance from commercial motors.', 'curated_seed', 'Wikimedia Commons (CC BY-SA 4.0)', true) on conflict (id) do nothing;
insert into experiences (id, experience_title, category, duration_minutes, price_per_head, maximum_capacity, lat, lng, city_id, neighborhood, tags, specialty_tier, vendor_id, one_line_teaser, full_description, indoor, wheelchair, step_free, senior_paced, low_sensory, hours, open_now, images, rating_score, rating_review_count, editorial_note, data_source, attribution, eligible_for_nearby_promotions) values ('exp-varanasi-02', 'Madanpura Banarasi Silk Handloom Weaving Atelier', 'workshops', 75, 250, 6, 25.3051, 83.0035, 'varanasi', 'Madanpura Weavers Quarter', ARRAY['banarasi silk', 'handloom weaving', 'zari', 'artisan family', 'independent'], 'hidden-gem', '092ca264-504b-48b9-91fd-fb8bbf5bb177', 'Watch master weavers guide pit-looms interlacing mulberry silk and pure gold zari threads.', 'Deep in the car-free alleys of Madanpura, master weaver Tariq Ansari demonstrates the Jacquard punch-card system controlling ancient pit-looms. Learn how a single intricate bridal saree requires up to six weeks of rhythmic foot and shuttle movement.', true, true, true, true, true, '10:00 - 17:30 (Mon - Sat)', true, ARRAY['https://images.unsplash.com/photo-1513519245088-0e12902e5a38?auto=format&fit=crop&w=900&q=80', 'https://images.unsplash.com/photo-1542314831-068cd1dbfeeb?auto=format&fit=crop&w=900&q=80'], 4.94, 112, 'Humbling master craft directly in the family ancestral home.', 'curated_seed', 'OpenStreetMap Contributors', true) on conflict (id) do nothing;
insert into experiences (id, experience_title, category, duration_minutes, price_per_head, maximum_capacity, lat, lng, city_id, neighborhood, tags, specialty_tier, vendor_id, one_line_teaser, full_description, indoor, wheelchair, step_free, senior_paced, low_sensory, hours, open_now, images, rating_score, rating_review_count, editorial_note, data_source, attribution, eligible_for_nearby_promotions) values ('exp-kolkata-01', 'Kumartuli Clay Idol Sculptors & Terracotta Studio Walk', 'workshops', 85, 300, 8, 22.6006, 88.3615, 'kolkata', 'North Kolkata / Kumartuli', ARRAY['clay idols', 'ganga clay sculpture', 'bengal heritage', 'independent'], 'hidden-gem', '2f6d1e51-f890-4b4f-ae31-4fe16f130ad8', 'Walk through narrow clay-scented ateliers watching artisans shape straw armatures and river clay into expressive statues.', 'Over 400 artisan families in Kumartuli have shaped sacred earthen sculptures for two and a half centuries using alluvial clay dredged from the Hooghly river. A resident sculptor demonstrates how straw, bamboo, and clay are layered and painted with organic tamarind-seed binders.', true, true, true, true, false, '09:00 - 18:00 (Daily)', true, ARRAY['https://images.unsplash.com/photo-1578749556568-bc2c40e68b61?auto=format&fit=crop&w=900&q=80', 'https://images.unsplash.com/photo-1565193566173-7a0ee3dbe261?auto=format&fit=crop&w=900&q=80'], 4.96, 142, 'Unfiltered access to a living medieval craft guild.', 'curated_seed', 'Wikimedia Commons (CC BY-SA 4.0)', true) on conflict (id) do nothing;
insert into experiences (id, experience_title, category, duration_minutes, price_per_head, maximum_capacity, lat, lng, city_id, neighborhood, tags, specialty_tier, vendor_id, one_line_teaser, full_description, indoor, wheelchair, step_free, senior_paced, low_sensory, hours, open_now, images, rating_score, rating_review_count, editorial_note, data_source, attribution, eligible_for_nearby_promotions) values ('exp-bengaluru-01', 'Malleswaram Traditional Filter Coffee Roasting & Tiffin Walk', 'food', 75, 220, 12, 13.0031, 77.5645, 'bengaluru', 'Malleswaram Heritage Precinct', ARRAY['filter coffee', 'chicory roasting', 'benne dosa', 'tiffin heritage'], 'signature', 'd09850d8-dc33-4ff4-a214-19e989ae0fed', 'Sample freshly roasted dark Peaberry chicory brew and crisp butter dosas at heritage South Indian coffee bars.', 'Malleswaram remains the cultural anchor of old Bengaluru. Led by a local culinary archivist, guests visit small-batch coffee roasters grinding beans from Chikmagalur estates, followed by tiffin tastings of hot idlis, vadas, and brass-tumbler frothy filter kaapi.', true, true, true, true, false, '07:30 - 16:30 (Daily)', true, ARRAY['https://images.unsplash.com/photo-1544787219-7f47ccb76574?auto=format&fit=crop&w=900&q=80', 'https://images.unsplash.com/photo-1576092768241-dec231879fc3?auto=format&fit=crop&w=900&q=80'], 4.89, 178, 'Invigorating morning atmosphere with century-old culinary recipes.', 'curated_seed', 'OpenStreetMap Contributors', true) on conflict (id) do nothing;
insert into experiences (id, experience_title, category, duration_minutes, price_per_head, maximum_capacity, lat, lng, city_id, neighborhood, tags, specialty_tier, vendor_id, one_line_teaser, full_description, indoor, wheelchair, step_free, senior_paced, low_sensory, hours, open_now, images, rating_score, rating_review_count, editorial_note, data_source, attribution, eligible_for_nearby_promotions) values ('exp-che-01', 'Mylapore Kolam Art & Filter Coffee Ritual', 'food', 60, 220, 10, 13.0339, 80.2695, 'chennai', 'Mylapore Temple Quarter', ARRAY['filter coffee', 'kolam art', 'temple heritage', 'morning ritual'], 'hidden-gem', '864d84ec-3cdd-4d46-aed3-57f7442976b9', 'Draw a traditional rice-flour kolam at dawn, then sample decoction filter coffee brewed the old Mylapore way.', 'Steps from the Kapaleeshwarar Temple gopuram, this family-run tiffin room has served filter coffee to the same streets for three generations. Guests learn the geometry of rice-flour kolam drawing on the threshold before sitting down to a tumbler-and-davara coffee service alongside crisp ghee roast dosas.', true, true, true, true, true, '06:30 - 11:00 (Daily)', true, ARRAY['https://images.unsplash.com/photo-1544787219-7f47ccb76574?auto=format&fit=crop&w=900&q=80', 'https://images.unsplash.com/photo-1585937421612-70a008356fbe?auto=format&fit=crop&w=900&q=80'], 4.9, 96, 'A genuinely local morning ritual, rarely seen by visitors.', 'curated_seed', 'Wikimedia Commons (CC BY-SA 4.0)', true) on conflict (id) do nothing;
insert into experiences (id, experience_title, category, duration_minutes, price_per_head, maximum_capacity, lat, lng, city_id, neighborhood, tags, specialty_tier, vendor_id, one_line_teaser, full_description, indoor, wheelchair, step_free, senior_paced, low_sensory, hours, open_now, images, rating_score, rating_review_count, editorial_note, data_source, attribution, eligible_for_nearby_promotions) values ('exp-che-02', 'Marina Bronze Casting & Nadaswaram Workshop', 'workshops', 90, 340, 6, 13.0475, 80.2824, 'chennai', 'Triplicane / Marina Coast', ARRAY['bronze casting', 'nadaswaram', 'lost-wax technique', 'classical music'], 'signature', '0b388a00-f947-49ab-a918-ea77e3e8e549', 'Watch lost-wax bronze idol casting up close, then try your hand at reed fingering on a nadaswaram.', 'A Triplicane workshop keeping the Thanjavur lost-wax casting tradition alive for Chennai’s temple festivals, paired with a rare chance to hold and sound a nadaswaram under a resident classical musician’s guidance. Visitors walk away understanding two crafts central to Tamil temple culture in a single sitting.', true, false, true, true, false, '15:00 - 19:00 (Tue - Sun)', false, ARRAY['https://images.unsplash.com/photo-1601924994987-69e26d50dc26?auto=format&fit=crop&w=900&q=80', 'https://images.unsplash.com/photo-1519669556878-63bdad8a1a49?auto=format&fit=crop&w=900&q=80'], 4.86, 61, 'Deep-craft access rarely opened to outside visitors.', 'curated_seed', 'Wikimedia Commons (CC BY-SA 4.0)', true) on conflict (id) do nothing;
insert into experiences (id, experience_title, category, duration_minutes, price_per_head, maximum_capacity, lat, lng, city_id, neighborhood, tags, specialty_tier, vendor_id, one_line_teaser, full_description, indoor, wheelchair, step_free, senior_paced, low_sensory, hours, open_now, images, rating_score, rating_review_count, editorial_note, data_source, attribution, eligible_for_nearby_promotions) values ('exp-hyd-01', 'Laad Bazaar Ittar Perfumery & Lacquer Bangle Workshop', 'workshops', 80, 280, 8, 17.3616, 78.4735, 'hyderabad', 'Old City / Charminar West', ARRAY['ittar perfume', 'lacquer bangles', 'mitti attar', 'nizami heritage'], 'hidden-gem', '7722c2f0-46c7-4358-92ea-659f61754c60', 'Blend hydro-distilled sandalwood and mitti (baked earth) oils and watch heated natural resin shaped into sparkling bangles.', 'Adjacent to the monumental Charminar arches, this family workshop has distilled natural essential oils for Nizami courts since the 19th century. Guests discover traditional copper deg-bhapka distillation and practice stone-setting on warm resin bangles.', true, true, true, true, true, '11:00 - 20:00 (Daily)', true, ARRAY['https://images.unsplash.com/photo-1528164344705-475426879c0d?auto=format&fit=crop&w=900&q=80', 'https://images.unsplash.com/photo-1545569341-9eb8b30979d9?auto=format&fit=crop&w=900&q=80'], 4.93, 132, 'Sensory storytelling rooted in centuries of royal court apothecary.', 'curated_seed', 'Wikimedia Commons (CC BY-SA 4.0)', true) on conflict (id) do nothing;
insert into experiences (id, experience_title, category, duration_minutes, price_per_head, maximum_capacity, lat, lng, city_id, neighborhood, tags, specialty_tier, vendor_id, one_line_teaser, full_description, indoor, wheelchair, step_free, senior_paced, low_sensory, hours, open_now, images, rating_score, rating_review_count, editorial_note, data_source, attribution, eligible_for_nearby_promotions) values ('exp-goa-01', 'Fontainhas Azulejos Hand-Painted Ceramic Tile Atelier', 'workshops', 90, 450, 8, 15.4989, 73.8278, 'goa', 'Fontainhas Latin Quarter / Panaji', ARRAY['azulejos', 'ceramic tiles', 'portuguese heritage', 'painting', 'independent'], 'hidden-gem', 'b6595d5a-7d03-4657-8f84-b744f26b591e', 'Paint cobalt blue Portuguese-Goan ceramic tiles with mineral glazes in a sunlit 19th-century ochre townhouse.', 'Surrounded by the terracotta-roofed villas of Fontainhas, this studio preserves the art of hand-painted glazed tin tiles (azulejos). Resident painters guide guests through traditional floral border motifs and maritime heraldry, followed by glaze firing.', true, true, true, true, true, '10:00 - 18:30 (Mon - Sat)', true, ARRAY['https://images.unsplash.com/photo-1518709268805-4e9042af9f23?auto=format&fit=crop&w=900&q=80', 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=900&q=80'], 4.92, 164, 'Relaxed creative workshop preserving Indo-Portuguese decorative craft.', 'curated_seed', 'Wikimedia Commons (CC BY-SA 4.0)', true) on conflict (id) do nothing;

-- 4. Offerings
insert into offerings (id, experience_id, title, price, description, duration_minutes) values ('off-d1', 'exp-delhi-01', 'Four Heritage Parantha Platter & Khari Baoli Rooftop', 350, 'Four traditional paranthas with pumpkin relish, mint chutney, and spice attic viewpoint.', 90) on conflict (id) do nothing;
insert into offerings (id, experience_id, title, price, description, duration_minutes) values ('off-d2', 'exp-delhi-01', 'Private Heritage Haveli Breakfast & Tea', 600, 'Exclusive courtyard seating inside a restored 18th-century Jain haveli.', 120) on conflict (id) do nothing;
insert into offerings (id, experience_id, title, price, description, duration_minutes) values ('off-d3', 'exp-delhi-02', 'Courtyard Qawwali Observation & Historical Walk', 0, 'Free communal gathering with optional donation toward baoli water conservation.', 75) on conflict (id) do nothing;
insert into offerings (id, experience_id, title, price, description, duration_minutes) values ('off-d4', 'exp-delhi-03', 'Two-Kulhad Throwing & Glazing Session', 450, 'Hands-on wheel instruction, trimming, and terracotta firing.', 90) on conflict (id) do nothing;
insert into offerings (id, experience_id, title, price, description, duration_minutes) values ('off-m1', 'exp-mumbai-01', 'Art Deco Architectural Walk & Irani Breakfast', 280, 'Guided 80-minute route with fresh bakery tasting and architectural monograph.', 80) on conflict (id) do nothing;
insert into offerings (id, experience_id, title, price, description, duration_minutes) values ('off-m2', 'exp-mumbai-02', 'Wholesale Flower Lane Walk & Kanda Poha', 150, 'Guided market interaction and hot freshly pressed poha with chai.', 60) on conflict (id) do nothing;
insert into offerings (id, experience_id, title, price, description, duration_minutes) values ('off-j1', 'exp-jaipur-01', 'Complete Cotton Stole Block Print Workshop', 500, 'All materials, raw indigo dipping, washing demonstration, and completed take-home stole.', 100) on conflict (id) do nothing;
insert into offerings (id, experience_id, title, price, description, duration_minutes) values ('off-j2', 'exp-jaipur-02', 'Lapidary Studio Demonstration & Tea', 320, 'Facet cutting demonstration, raw gemstone identification, and chai.', 70) on conflict (id) do nothing;
insert into offerings (id, experience_id, title, price, description, duration_minutes) values ('off-k1', 'exp-kochi-01', 'Six-Spice Comparative Tasting Flight', 250, 'Direct origin tastings of cardamom, pepper varieties, and heirloom cinnamon.', 75) on conflict (id) do nothing;
insert into offerings (id, experience_id, title, price, description, duration_minutes) values ('off-k2', 'exp-kochi-02', 'Makeup Session & Full Performance Recital', 300, 'Complete backstage makeup observation and evening story performance.', 90) on conflict (id) do nothing;
insert into offerings (id, experience_id, title, price, description, duration_minutes) values ('off-v1', 'exp-varanasi-01', 'Quiet Dawn Rowing & Classical Music Stop', 200, 'Hand-rowed boat with life jackets, tea stop, and riverside sitar viewing.', 80) on conflict (id) do nothing;
insert into offerings (id, experience_id, title, price, description, duration_minutes) values ('off-v2', 'exp-varanasi-02', 'Pit-Loom Demonstration & Zari Testing', 250, 'Hands-on shuttle throwing, silk grading, and keepsake weave sample.', 75) on conflict (id) do nothing;
insert into offerings (id, experience_id, title, price, description, duration_minutes) values ('off-kol1', 'exp-kolkata-01', 'Studio Sculpture Demonstration & Earthen Mask', 300, 'Sculpting demonstration with small take-home terracotta terracotta keepsake.', 85) on conflict (id) do nothing;
insert into offerings (id, experience_id, title, price, description, duration_minutes) values ('off-b1', 'exp-bengaluru-01', 'Tiffin Trail & Filter Coffee Master Roasting', 220, 'Three tiffin tastings, bean roasting demo, and brass dabara tumbler coffee.', 75) on conflict (id) do nothing;
insert into offerings (id, experience_id, title, price, description, duration_minutes) values ('off-c1', 'exp-che-01', 'Kolam Drawing Lesson & Filter Coffee Tasting Flight', 220, 'Hands-on kolam practice followed by a three-pour filter coffee tasting with tiffin snacks.', 60) on conflict (id) do nothing;
insert into offerings (id, experience_id, title, price, description, duration_minutes) values ('off-c2', 'exp-che-02', 'Bronze Casting Demonstration & Nadaswaram Trial', 340, 'Guided foundry walkthrough plus a supervised nadaswaram fingering lesson.', 90) on conflict (id) do nothing;
insert into offerings (id, experience_id, title, price, description, duration_minutes) values ('off-h1', 'exp-hyd-01', 'Personalized Ittar Formulation & Bangle Trial', 280, 'Craft your own 6ml botanical scent vial and customize a pair of bangles.', 80) on conflict (id) do nothing;
insert into offerings (id, experience_id, title, price, description, duration_minutes) values ('off-g1', 'exp-goa-01', 'Two-Tile Azulejo Painting & Firing', 450, 'Two ceramic bisque tiles, cobalt mineral glazes, kiln firing, and packaging.', 90) on conflict (id) do nothing;

-- 5. Availability slots
insert into availability_slots (id, experience_id, date, time, capacity_remaining, total_capacity) values ('s-d1', 'exp-delhi-01', '2026-09-27', '09:00', 4, 10) on conflict (id) do nothing;
insert into availability_slots (id, experience_id, date, time, capacity_remaining, total_capacity) values ('s-d2', 'exp-delhi-01', '2026-09-27', '12:00', 6, 10) on conflict (id) do nothing;
insert into availability_slots (id, experience_id, date, time, capacity_remaining, total_capacity) values ('s-d3', 'exp-delhi-02', '2026-09-27', '17:30', 15, 25) on conflict (id) do nothing;
insert into availability_slots (id, experience_id, date, time, capacity_remaining, total_capacity) values ('s-d4', 'exp-delhi-03', '2026-09-27', '11:00', 3, 6) on conflict (id) do nothing;
insert into availability_slots (id, experience_id, date, time, capacity_remaining, total_capacity) values ('s-d5', 'exp-delhi-03', '2026-09-27', '15:00', 2, 6) on conflict (id) do nothing;
insert into availability_slots (id, experience_id, date, time, capacity_remaining, total_capacity) values ('s-m1', 'exp-mumbai-01', '2026-09-27', '08:30', 5, 12) on conflict (id) do nothing;
insert into availability_slots (id, experience_id, date, time, capacity_remaining, total_capacity) values ('s-m2', 'exp-mumbai-01', '2026-09-27', '10:30', 8, 12) on conflict (id) do nothing;
insert into availability_slots (id, experience_id, date, time, capacity_remaining, total_capacity) values ('s-m3', 'exp-mumbai-02', '2026-09-27', '06:30', 6, 10) on conflict (id) do nothing;
insert into availability_slots (id, experience_id, date, time, capacity_remaining, total_capacity) values ('s-m4', 'exp-mumbai-02', '2026-09-27', '08:00', 3, 10) on conflict (id) do nothing;
insert into availability_slots (id, experience_id, date, time, capacity_remaining, total_capacity) values ('s-j1', 'exp-jaipur-01', '2026-09-27', '10:00', 4, 8) on conflict (id) do nothing;
insert into availability_slots (id, experience_id, date, time, capacity_remaining, total_capacity) values ('s-j2', 'exp-jaipur-01', '2026-09-27', '14:00', 5, 8) on conflict (id) do nothing;
insert into availability_slots (id, experience_id, date, time, capacity_remaining, total_capacity) values ('s-j3', 'exp-jaipur-02', '2026-09-27', '11:30', 3, 8) on conflict (id) do nothing;
insert into availability_slots (id, experience_id, date, time, capacity_remaining, total_capacity) values ('s-j4', 'exp-jaipur-02', '2026-09-27', '15:30', 4, 8) on conflict (id) do nothing;
insert into availability_slots (id, experience_id, date, time, capacity_remaining, total_capacity) values ('s-k1', 'exp-kochi-01', '2026-09-27', '10:00', 5, 12) on conflict (id) do nothing;
insert into availability_slots (id, experience_id, date, time, capacity_remaining, total_capacity) values ('s-k2', 'exp-kochi-01', '2026-09-27', '14:30', 7, 12) on conflict (id) do nothing;
insert into availability_slots (id, experience_id, date, time, capacity_remaining, total_capacity) values ('s-k3', 'exp-kochi-02', '2026-09-27', '17:00', 8, 16) on conflict (id) do nothing;
insert into availability_slots (id, experience_id, date, time, capacity_remaining, total_capacity) values ('s-v1', 'exp-varanasi-01', '2026-09-27', '05:45', 4, 10) on conflict (id) do nothing;
insert into availability_slots (id, experience_id, date, time, capacity_remaining, total_capacity) values ('s-v2', 'exp-varanasi-02', '2026-09-27', '10:30', 3, 6) on conflict (id) do nothing;
insert into availability_slots (id, experience_id, date, time, capacity_remaining, total_capacity) values ('s-v3', 'exp-varanasi-02', '2026-09-27', '14:00', 4, 6) on conflict (id) do nothing;
insert into availability_slots (id, experience_id, date, time, capacity_remaining, total_capacity) values ('s-kol1', 'exp-kolkata-01', '2026-09-27', '10:00', 5, 8) on conflict (id) do nothing;
insert into availability_slots (id, experience_id, date, time, capacity_remaining, total_capacity) values ('s-b1', 'exp-bengaluru-01', '2026-09-27', '08:00', 6, 12) on conflict (id) do nothing;
insert into availability_slots (id, experience_id, date, time, capacity_remaining, total_capacity) values ('s-c1', 'exp-che-01', '2026-09-27', '07:00', 6, 10) on conflict (id) do nothing;
insert into availability_slots (id, experience_id, date, time, capacity_remaining, total_capacity) values ('s-c2', 'exp-che-02', '2026-09-27', '15:30', 3, 6) on conflict (id) do nothing;
insert into availability_slots (id, experience_id, date, time, capacity_remaining, total_capacity) values ('s-h1', 'exp-hyd-01', '2026-09-27', '11:30', 4, 8) on conflict (id) do nothing;
insert into availability_slots (id, experience_id, date, time, capacity_remaining, total_capacity) values ('s-g1', 'exp-goa-01', '2026-09-27', '10:30', 3, 8) on conflict (id) do nothing;
insert into availability_slots (id, experience_id, date, time, capacity_remaining, total_capacity) values ('s-g2', 'exp-goa-01', '2026-09-27', '15:00', 5, 8) on conflict (id) do nothing;

-- 6. Search demand signals
insert into search_demand_signals (id, vendor_id, city_id, query_tags, category, searches_count, trend_percentage, avg_budget_indicated, accessibility_demand, neighborhood_focus) values ('sig-delhi-01', NULL, 'delhi', ARRAY['wheelchair accessible', 'old delhi street food', 'evening', 'under Rs 500'], 'food', 248, 34, 400, 'Step-free access & slow pacing requested in 72% of queries', 'Chandni Chowk & Daryaganj') on conflict (id) do nothing;
insert into search_demand_signals (id, vendor_id, city_id, query_tags, category, searches_count, trend_percentage, avg_budget_indicated, accessibility_demand, neighborhood_focus) values ('sig-mum-01', NULL, 'mumbai', ARRAY['art deco walking tour', 'heritage bakery', 'morning slot', 'step-free'], 'culture', 312, 26, 350, 'Paved flat sidewalks & shade stops preferred', 'Fort & Kala Ghoda') on conflict (id) do nothing;
insert into search_demand_signals (id, vendor_id, city_id, query_tags, category, searches_count, trend_percentage, avg_budget_indicated, accessibility_demand, neighborhood_focus) values ('sig-jai-01', NULL, 'jaipur', ARRAY['dabu block printing workshop', 'hands-on craft', 'village atelier', 'couple'], 'workshops', 420, 42, 600, 'Wheelchair ramp and ground-floor washrooms prioritized', 'Bagru & Sanganer Clusters') on conflict (id) do nothing;
insert into search_demand_signals (id, vendor_id, city_id, query_tags, category, searches_count, trend_percentage, avg_budget_indicated, accessibility_demand, neighborhood_focus) values ('sig-koc-01', NULL, 'kochi', ARRAY['kathakali makeup observation', 'classical arts', 'evening', 'family'], 'culture', 185, 19, 300, 'Chair seating with back support requested for seniors', 'Fort Kochi') on conflict (id) do nothing;
insert into search_demand_signals (id, vendor_id, city_id, query_tags, category, searches_count, trend_percentage, avg_budget_indicated, accessibility_demand, neighborhood_focus) values ('sig-var-01', NULL, 'varanasi', ARRAY['dawn hand-rowed boat', 'classical sitar', 'spiritual', 'silent'], 'nature', 530, 51, 250, 'Gentle step boarding assistance and quiet acoustics', 'Assi to Dashashwamedh') on conflict (id) do nothing;
