import React from 'react';
import { useApp } from '../../context/AppContext';

export const TermsOfService: React.FC = () => {
  const { navigateTo } = useApp();

  return (
    <div className="max-w-4xl mx-auto space-y-6">
      <div className="bg-white border border-[#E2E6EC] rounded-[4px] p-6 sm:p-10 space-y-6">
        <div className="border-b border-[#E2E6EC] pb-4">
          <div className="text-[11px] uppercase font-semibold text-[#5B7A99] tracking-wider">
            Legal Agreement
          </div>
          <h1 className="text-3xl font-serif font-bold text-[#111827] mt-1">
            Terms of Service
          </h1>
          <p className="text-xs text-[#6B7280] mt-1">
            Effective Date: September 2026. Version 1.2.
          </p>
        </div>

        <section className="space-y-2 text-xs text-[#4B5563] leading-relaxed">
          <h2 className="text-sm font-semibold uppercase tracking-wider text-[#111827]">
            1. Platform Purpose & Scope
          </h2>
          <p>
            Passage provides an intelligent local discovery and dynamic tour planning software interface. We connect travelers directly with independent artisans, tea merchants, culinary studios, and cultural venues. Passage is not a conventional tour operator or package seller; all itineraries generated by the platform are self-directed, direct-manipulation route proposals configured by the user.
          </p>
        </section>

        <section className="space-y-2 text-xs text-[#4B5563] leading-relaxed">
          <h2 className="text-sm font-semibold uppercase tracking-wider text-[#111827]">
            2. Dynamic Route Calculation & Field Realities
          </h2>
          <p>
            Route durations, walking distances, and public transit schedules are computed based on cartographic graph models and municipal transport estimates. While our constraint engine optimizes for efficiency and accessibility, actual travel conditions may vary due to weather, regional festivities, transit delays, or unexpected street closures. Travelers are expected to exercise customary prudence and situational awareness while navigating.
          </p>
        </section>

        <section className="space-y-2 text-xs text-[#4B5563] leading-relaxed">
          <h2 className="text-sm font-semibold uppercase tracking-wider text-[#111827]">
            3. Direct Merchant Relationship & Verification
          </h2>
          <p>
            Offerings, workshop fees, and slot capacities published in the platform originate directly from the verified merchants and guilds. When you reserve a session or add an experience to your dynamic itinerary, you are entering into a direct patronage agreement with that local business. Passage enforces verified merchant standards but is not an agent or employer of independent artisans.
          </p>
        </section>

        <section className="space-y-2 text-xs text-[#4B5563] leading-relaxed">
          <h2 className="text-sm font-semibold uppercase tracking-wider text-[#111827]">
            4. Accessibility Verification Standards
          </h2>
          <p>
            Venues marked with step-free or wheelchair accessibility attributes have completed our spatial verification protocol. However, historic urban environments (including stone pavement and narrow alleys) may present localized physical barriers. We encourage travelers with strict accessibility needs to review the individual vendor profile notes.
          </p>
        </section>

        <section className="space-y-2 text-xs text-[#4B5563] leading-relaxed">
          <h2 className="text-sm font-semibold uppercase tracking-wider text-[#111827]">
            5. Disruption Management & Cancellations
          </h2>
          <p>
            Our quick-action disruption engine allows you to adapt itineraries immediately in response to weather or spot closures. In the event an artisan workshop or private tea tasting must cancel due to unforeseen circumstances, the affected merchant will refund any prepaid booking fees according to their stated policy, and our system will assist in slotting an immediate nearby alternative.
          </p>
        </section>

        <div className="pt-6 border-t border-[#E2E6EC] flex items-center justify-between">
          <button
            onClick={() => navigateTo('explore')}
            className="px-4 py-2 bg-[#1B3A6B] text-white text-xs font-semibold rounded-[2px] hover:bg-[#152e55] transition-colors"
          >
            Return to Explore
          </button>
          <span className="text-[11px] text-[#9CA3AF]">
            Governing Law: Republic of India, National Jurisdiction
          </span>
        </div>
      </div>
    </div>
  );
};
